apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/lambda-create-function@v1
        name: Say hello
        with:
          function-name: name
          iam-role-arn: resource
          publish: true
          dry-run: true
